import logging

"""
ENVIRONMENT CONFIG
"""
WINDOW_HEIGHT = 800
WINDOW_WIDTH = 600
USE_STROKE = False
LOG_DIR = './log'

"""
MAIN CONFIG
"""
STAR_COLOR = color(255,255,0)

PHASE_1 = WINDOW_HEIGHT * 0.05
PHASE_2 = WINDOW_HEIGHT * 0.1
PHASE_3 = WINDOW_HEIGHT * 0.3
PHASE_4 = WINDOW_HEIGHT * 0.5
PHASE_5 = WINDOW_HEIGHT * 0.7
PHASE_6 = WINDOW_HEIGHT * 0.99
PHASE_7 = WINDOW_HEIGHT

GROW_SPEED = 3

"""
ORDER:
    DEBUG -> INFO -> WARNING -> ERROR -> CRITICAL  
"""
LOG_LEVEL = logging.INFO
