import colors

bird_V1 = []
bird_V1.append([colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.VIOLET, colors.VIOLET, colors.VIOLET, colors.EMPTY,      colors.EMPTY,      colors.EMPTY])
bird_V1.append([colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.VIOLET, colors.VIOLET, colors.VIOLET, colors.VIOLET, colors.VIOLET, colors.EMPTY,      colors.EMPTY])
bird_V1.append([colors.VIOLET,     colors.VIOLET,     colors.VIOLET,     colors.EMPTY,      colors.EMPTY,      colors.VIOLET, colors.VIOLET, colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.VIOLET, colors.EMPTY])
bird_V1.append([colors.VIOLET,     colors.VIOLET,     colors.VIOLET,     colors.VIOLET,     colors.EMPTY,      colors.VIOLET, colors.VIOLET, colors.WHITE,      colors.WHITE,      colors.BLACK,      colors.WHITE,      colors.VIOLET, colors.EMPTY]) 
bird_V1.append([colors.VIOLET,     colors.VIOLET,     colors.VIOLET,     colors.VIOLET,     colors.VIOLET, colors.VIOLET, colors.VIOLET, colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.YELLOW,     colors.YELLOW])
bird_V1.append([colors.VIOLET,     colors.VIOLET,     colors.VIOLET,     colors.VIOLET,     colors.VIOLET, colors.VIOLET, colors.VIOLET, colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.VIOLET, colors.EMPTY,      colors.EMPTY])
bird_V1.append([colors.VIOLET,     colors.VIOLET,     colors.VIOLET,     colors.VIOLET,     colors.VIOLET, colors.VIOLET, colors.VIOLET, colors.VIOLET, colors.VIOLET, colors.VIOLET, colors.EMPTY,      colors.EMPTY,      colors.EMPTY])
bird_V1.append([colors.EMPTY,      colors.VIOLET,     colors.VIOLET,     colors.VIOLET,     colors.VIOLET, colors.VIOLET, colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY])
bird_V1.append([colors.EMPTY,      colors.EMPTY,      colors.VIOLET,     colors.VIOLET,     colors.VIOLET, colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY])
bird_V1.append([colors.EMPTY,      colors.VIOLET,     colors.VIOLET,     colors.VIOLET,     colors.VIOLET, colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY])
bird_V1.append([colors.EMPTY,      colors.VIOLET,     colors.VIOLET,     colors.VIOLET,     colors.VIOLET, colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY])
bird_V1.append([colors.EMPTY,      colors.EMPTY,      colors.VIOLET,     colors.VIOLET,     colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY])

bird_V2 = []
bird_V2.append([colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.LIMEGREEN, colors.LIMEGREEN, colors.LIMEGREEN, colors.EMPTY,      colors.EMPTY,      colors.EMPTY])
bird_V2.append([colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.LIMEGREEN, colors.LIMEGREEN, colors.LIMEGREEN, colors.LIMEGREEN, colors.LIMEGREEN, colors.EMPTY,      colors.EMPTY])
bird_V2.append([colors.LIMEGREEN,  colors.LIMEGREEN,  colors.LIMEGREEN,  colors.EMPTY,      colors.EMPTY,      colors.LIMEGREEN, colors.LIMEGREEN, colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.LIMEGREEN, colors.EMPTY])
bird_V2.append([colors.LIMEGREEN,  colors.LIMEGREEN,  colors.LIMEGREEN,  colors.LIMEGREEN, colors.EMPTY,      colors.LIMEGREEN, colors.LIMEGREEN, colors.WHITE,      colors.WHITE,      colors.BLACK,      colors.WHITE,      colors.LIMEGREEN, colors.EMPTY]) 
bird_V2.append([colors.LIMEGREEN,  colors.LIMEGREEN,  colors.LIMEGREEN,  colors.LIMEGREEN, colors.LIMEGREEN, colors.LIMEGREEN, colors.LIMEGREEN, colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.YELLOW,     colors.YELLOW])
bird_V2.append([colors.LIMEGREEN,  colors.LIMEGREEN,  colors.LIMEGREEN,  colors.LIMEGREEN, colors.LIMEGREEN, colors.LIMEGREEN, colors.LIMEGREEN, colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.LIMEGREEN, colors.EMPTY,      colors.EMPTY])
bird_V2.append([colors.LIMEGREEN,  colors.LIMEGREEN,  colors.LIMEGREEN,  colors.LIMEGREEN, colors.LIMEGREEN, colors.LIMEGREEN, colors.LIMEGREEN, colors.LIMEGREEN, colors.LIMEGREEN, colors.LIMEGREEN, colors.EMPTY,      colors.EMPTY,      colors.EMPTY])
bird_V2.append([colors.EMPTY,      colors.LIMEGREEN,  colors.LIMEGREEN,  colors.LIMEGREEN, colors.LIMEGREEN, colors.LIMEGREEN, colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY])
bird_V2.append([colors.EMPTY,      colors.EMPTY,      colors.LIMEGREEN,  colors.LIMEGREEN, colors.LIMEGREEN, colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY])
bird_V2.append([colors.EMPTY,      colors.LIMEGREEN,  colors.LIMEGREEN,  colors.LIMEGREEN, colors.LIMEGREEN, colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY])
bird_V2.append([colors.EMPTY,      colors.LIMEGREEN,  colors.LIMEGREEN,  colors.LIMEGREEN, colors.LIMEGREEN, colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY])
bird_V2.append([colors.EMPTY,      colors.EMPTY,      colors.LIMEGREEN,  colors.LIMEGREEN, colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY])

bird_V3 = []
bird_V3.append([colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.EMPTY,      colors.EMPTY,      colors.EMPTY])
bird_V3.append([colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.EMPTY,      colors.EMPTY])
bird_V3.append([colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.EMPTY,      colors.EMPTY,      colors.POWDERBLUE, colors.POWDERBLUE, colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.POWDERBLUE, colors.EMPTY])
bird_V3.append([colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.EMPTY,      colors.POWDERBLUE, colors.POWDERBLUE, colors.WHITE,      colors.WHITE,      colors.BLACK,      colors.WHITE,      colors.POWDERBLUE, colors.EMPTY]) 
bird_V3.append([colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.YELLOW,     colors.YELLOW])
bird_V3.append([colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.POWDERBLUE, colors.EMPTY,      colors.EMPTY])
bird_V3.append([colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.EMPTY,      colors.EMPTY,      colors.EMPTY])
bird_V3.append([colors.EMPTY,      colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY])
bird_V3.append([colors.EMPTY,      colors.EMPTY,      colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY])
bird_V3.append([colors.EMPTY,      colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY])
bird_V3.append([colors.EMPTY,      colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.POWDERBLUE, colors.WHITE,      colors.WHITE,      colors.WHITE,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY])
bird_V3.append([colors.EMPTY,      colors.EMPTY,      colors.POWDERBLUE, colors.POWDERBLUE, colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY,      colors.EMPTY])


cloud1 = []
cloud1.append([colors.EMPTY, colors.EMPTY, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.EMPTY, colors.EMPTY])
cloud1.append([colors.EMPTY, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.EMPTY])
cloud1.append([colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE])
cloud1.append([colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE])
cloud1.append([colors.EMPTY, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.EMPTY])
cloud1.append([colors.EMPTY, colors.EMPTY, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.WHITE, colors.EMPTY, colors.EMPTY])

pocket = []
pocket.append([colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.BROWN,colors.BROWN,colors.BROWN,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY])
pocket.append([colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.BROWN,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY])
pocket.append([colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.BROWN,colors.BROWN,colors.BROWN,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY])
pocket.append([colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY])
pocket.append([colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.EMPTY,colors.EMPTY,colors.EMPTY])
pocket.append([colors.EMPTY,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.EMPTY])
pocket.append([colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN])
pocket.append([colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.WHITE,colors.BROWN,colors.BROWN,colors.BROWN])
pocket.append([colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.WHITE,colors.BROWN,colors.BROWN,colors.BROWN])
pocket.append([colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.WHITE,colors.BROWN,colors.BROWN,colors.BROWN,colors.EMPTY])
pocket.append([colors.EMPTY,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.EMPTY,colors.EMPTY])
pocket.append([colors.EMPTY,colors.EMPTY,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.BROWN,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY])

haff = []
haff.append([colors.YELLOW,colors.YELLOW,colors.YELLOW,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY])
haff.append([colors.EMPTY,colors.YELLOW,colors.EMPTY,colors.YELLOW,colors.YELLOW,colors.EMPTY,colors.EMPTY])
haff.append([colors.EMPTY,colors.YELLOW,colors.EMPTY,colors.BROWN,colors.EMPTY,colors.YELLOW,colors.EMPTY])
haff.append([colors.EMPTY,colors.YELLOW,colors.EMPTY,colors.BROWN,colors.EMPTY,colors.BROWN,colors.YELLOW])
haff.append([colors.EMPTY,colors.YELLOW,colors.EMPTY,colors.BROWN,colors.EMPTY,colors.BROWN,colors.YELLOW])
haff.append([colors.EMPTY,colors.YELLOW,colors.EMPTY,colors.BROWN,colors.EMPTY,colors.BROWN,colors.YELLOW])
haff.append([colors.EMPTY,colors.YELLOW,colors.EMPTY,colors.BROWN,colors.EMPTY,colors.BROWN,colors.YELLOW])
haff.append([colors.EMPTY,colors.YELLOW,colors.EMPTY,colors.BROWN,colors.EMPTY,colors.BROWN,colors.EMPTY])
haff.append([colors.EMPTY,colors.YELLOW,colors.EMPTY,colors.YELLOW,colors.YELLOW,colors.EMPTY,colors.EMPTY])
haff.append([colors.YELLOW,colors.YELLOW,colors.YELLOW,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY])

chicken = []
chicken.append([colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.RED, colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY])
chicken.append([colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.RED,colors.RED,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY])
chicken.append([colors.EMPTY,colors.EMPTY,colors.WHITE,colors.WHITE,colors.WHITE,colors.WHITE,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY])
chicken.append([colors.EMPTY,colors.EMPTY,colors.WHITE,colors.WHITE,colors.WHITE,colors.WHITE,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY])
chicken.append([colors.EMPTY,colors.EMPTY,colors.WHITE,colors.GRAY_C,colors.WHITE,colors.WHITE,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY])
chicken.append([colors.RED,colors.RED,colors.WHITE,colors.WHITE,colors.WHITE,colors.WHITE,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY])
chicken.append([colors.EMPTY,colors.RED,colors.WHITE,colors.WHITE,colors.WHITE,colors.WHITE,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.EMPTY])
chicken.append([colors.EMPTY,colors.EMPTY,colors.WHITE,colors.WHITE,colors.WHITE,colors.WHITE,colors.WHITE,colors.WHITE,colors.WHITE,colors.WHITE,colors.WHITE,])
chicken.append([colors.EMPTY,colors.EMPTY,colors.WHITE,colors.WHITE,colors.WHITE,colors.WHITE,colors.GRAY_C,colors.GRAY_C,colors.WHITE,colors.WHITE,colors.WHITE,])
chicken.append([colors.EMPTY,colors.EMPTY,colors.WHITE,colors.WHITE,colors.WHITE,colors.WHITE,colors.WHITE,colors.WHITE,colors.GRAY_C,colors.WHITE,colors.WHITE,])
chicken.append([colors.EMPTY,colors.EMPTY,colors.WHITE,colors.WHITE,colors.WHITE,colors.WHITE,colors.GRAY_C,colors.GRAY_C,colors.WHITE,colors.WHITE,colors.WHITE,])
chicken.append([colors.EMPTY,colors.EMPTY,colors.WHITE,colors.WHITE,colors.WHITE,colors.WHITE,colors.WHITE,colors.WHITE,colors.WHITE,colors.WHITE,colors.WHITE,])
chicken.append([colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.RED,colors.EMPTY,colors.EMPTY,colors.EMPTY,colors.RED,colors.EMPTY,colors.EMPTY,colors.EMPTY])
chicken.append([colors.EMPTY,colors.EMPTY,colors.RED,colors.RED,colors.RED,colors.EMPTY,colors.RED,colors.RED,colors.RED,colors.EMPTY,colors.EMPTY])

wire = []
wire.append([colors.WIRE_LIGHT, colors.WIRE_LIGHT, colors.WIRE_DARK])
